package routing

type Key_MPTCPReceiverKey_ int64

/*
   The token is used to identify the MPTCP connection and is a
   cryptographic hash of the receiver's key, as exchanged in the initial
   MP_CAPABLE handshake (Section 3.1).  In this specification, the
   tokens presented in this option are generated by the SHA-1 ([4],
   [15]) algorithm, truncated to the most significant 32 bits.

	https://tools.ietf.org/html/rfc6824#section-3.1
 */
type Key_MPTCPReceiverToken_ int32

